os: linux

sudo: required
services: docker

before_install:
  - docker build -t angular2ts-starter-kit .
  - docker run -dit --name app angular2ts-starter-kit
  - docker-compose up -d

script:
  - docker exec -it app npm run build
  - docker-compose exec app npm run build
