os: linux

sudo: required
services: docker

before_install:
  - docker-compose up -d

script:
  - docker-compose exec app npm run build
  - docker-compose exec app npm run lint
  - docker-compose exec app npm run unit
  # - docker-compose exec app npm run e2e
