language: node_js
node_js:
  - 4
  - 5
  - 6

sudo: false

cache:
  directories: node_modules

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nohup bash -c webdriver-manager start 2>&1 &
  - sleep 1

script:
  - gulp build
  # - gulp lint
  # - gulp unit
  # - gulp e2e
