language: node_js

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      node_js: stable
    - os: osx
      sudo: false
      node_js: stable

cache:
  directories: node_modules

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t angular2ts-starter-kit .; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -d --name app angular2ts-starter-kit; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker ps -a; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nohup bash -c "webdriver-manager start 2>&1 &"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi

before_script:
  - npm install karma-firefox-launcher

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -p 3000:3000 -d angular2ts-starter-kit; fi
  - npm run gulp -- build
  - npm run gulp -- lint
  # - npm run gulp -- unit
  - npm run gulp -- e2e
